### ISSUE TITLE
20 mv of noise on a reference ground

### ISSUE THREAD

**Issue by bjbeare** [Ho-Ro/openhantek#6]
I'm seeing about 20mv of noise on the reference ground. Also the two channels have about a 40mv difference in the average DC level of the ground. Picture attached.

Does this seem normal for the 6022BE?

Thanks!
![Screenshot from 2019-03-17 10-12-19](https://user-images.githubusercontent.com/1189877/54495044-9518b300-489d-11e9-90b2-e01f7560320b.png)

**Comment by bjbeare** [comment]
Ah... upon further research, this level of noise isn't at all unusual. The real issue is that there is no way to calibrate the "zero" each channel. I saw some discussion of this in the original openhantek project.

Are you working on putting in calibration?
If not... I make take a look.

**Comment by Ho-Ro** [comment]
Hi bjbeare,
Yes, unfortunately this is normal behaviour out of the box due to the brain-damaged hw design - the ADC is operated far outside its input voltage specs (common mode voltage of this single supply ADC should be biased to +0.9V but /Ain is pulled to GND) in order to measure -0.5V .. +0.5V on Ain.
![image](https://user-images.githubusercontent.com/12542359/54520256-9662e200-4968-11e9-94d8-776625703e7c.png) 
Equivalent circuit diagram of AD9288 input stage

To circumvent this and also the gain unaccuracy due to widely tolerated resistors in the frontend I've implemented a calibration method for offset as well as gain: https://github.com/Ho-Ro/openhantek/blob/master/openhantek/src/hantekdso/models/modelDSO6022.conf - please test.
This is a 1st shot in the dark, I'm thinking about using the offset calibration values stored in EEPROM (factory setting) as well as a method to autozero (and in a further step) to autocalibrate (with storage in EEPROM) - probably as a stand-alone application, e.g. in python. -> https://github.com/Ho-Ro/Hantek6022API
I close this issue because a calibration method is in place - as soon as we have something new I will comment here.
Martin
@bjbeare did you check the solution with the calibration file? you have to find your own optimal values but in the end you will come down to about +- 2mV in the sensitive ranges.

**Comment by bjbeare** [comment]
@Ho-Ro Just saw your response. Wow... great information there. I'll give it a try.
