### ISSUE TITLE
Wrong frequency value in markers tool-window

### ISSUE THREAD

**Issue by iss000** [Ho-Ro/openhantek#9]
Just found small bug in markers tool-window. See attached picture.
Else, thank you for your effort - with your development my 6022BL is not a toy anymore! :)
![freq-issue](https://user-images.githubusercontent.com/1128663/56519263-4d471480-654a-11e9-935e-e7fc984bf3d2.png)

**Comment by Ho-Ro** [comment]
Thx iss000, fixed by 0badee2

**Comment by Ho-Ro** [comment]
One remark:
I think the original idea behind these values was to measure time on the time axis of the samples and frequency on the frequency axis of the spectrum. However, this approach contradicts the two values marked in green in the footer and is confusing if no spectrum is displayed at all.
The individual rectangular cursors of this marker section are also better suited for this type of measurement.
I'm working with OpenHantek since the beginning of the year and slowly understand the philosophy of the program, nevertheless I've already made some annoying behavior more usable. So it's especially important to get your feedback and that of other users.
